POST http://localhost:3001/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZkZGM5OGMxLWVjZjEtNGNmOS04ZDYwLTdhNmViOTBiOWRjMCIsInVzZXJuYW1lIjoicXdlIiwiZW1haWwiOiJxd2VAZy5jIiwiam9pbmVkU3VicmliYml0cyI6Int9IiwiY3JlYXRlZEF0IjoiMjAyMC0xMi0yNlQwNjozODo0MS4xNzVaIiwia2FybWEiOiIxIiwiaWF0IjoxNjA5MTc5MDIzfQ.L5aQ2s1l4DJgyQGOE6SxMSiy9K6DIBrhPF7deqxyWb0

{
  "sub": "QWEsLair",
  "title": "Post 22",
  "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
}