PATCH http://localhost:3001/api/subribbits/join/qwe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiOTUzNzFhLTFjZmEtNGM3YS04ZDE4LWQ2YmRkMjE5NDBkOCIsInVzZXJuYW1lIjoiYm9iIiwiZW1haWwiOiJib2JAZy5jb20iLCJqb2luZWRTdWJyaWJiaXRzIjoie30iLCJpYXQiOjE2MDg3MjQwMjN9.fqEC8zh1WJywIXyoxqxhuQ5XBtCCosvuvxPlNVvng3E
